// <auto-generated />
using System;
using Camp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Camp.Data.Migrations
{
    [DbContext(typeof(CampContext))]
    [Migration("20191121033651_bunkname")]
    partial class bunkname
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Camp.Data.Bunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BunkName");

                    b.HasKey("Id");

                    b.ToTable("Bunk");
                });

            modelBuilder.Entity("Camp.Data.Camper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<bool>("Allergies");

                    b.Property<string>("AllergyFoods");

                    b.Property<DateTime>("Birthday");

                    b.Property<int?>("BunkId");

                    b.Property<string>("BunkName");

                    b.Property<string>("EmergencyContactFirstName");

                    b.Property<string>("EmergencyContactLastName");

                    b.Property<string>("EmergencyContactPhoneNumber");

                    b.Property<string>("FatherFirstName");

                    b.Property<string>("FatherLastName");

                    b.Property<string>("FatherPhoneNumber");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MotherFirstName");

                    b.Property<string>("MotherLastName");

                    b.Property<string>("MotherPhoneNumber");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("BunkId");

                    b.ToTable("Campers");
                });

            modelBuilder.Entity("Camp.Data.Camper", b =>
                {
                    b.HasOne("Camp.Data.Bunk")
                        .WithMany("Campers")
                        .HasForeignKey("BunkId");
                });
#pragma warning restore 612, 618
        }
    }
}
